version: '3.8'

services:
  app:
    build: .
    container_name: fastapi-app
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
      - DYNAMODB_HOST=http://localstack:4566
      - SES_HOST=http://localstack:4566
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - localstack

  worker:
    build: .
    container_name: celery-worker
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
      - DYNAMODB_HOST=http://localstack:4566
      - SES_HOST=http://localstack:4566
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: celery -A app.tasks.tasks worker --loglevel=info
    depends_on:
      - redis
      - localstack

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  localstack:
    image: localstack/localstack
    container_name: localstack
    environment:
      - SERVICES=dynamodb, ses
      - DEBUG=1
    ports:
      - "4566:4566"
      - "4571:4571"
